### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by HamedNN76** [HamedNN76/postman-fetch#4]
A complete readme file:
- [x] Installing the package
- [x] PostmanFetch class parameters
- [x] Usage of the package
- [x] Link to example project
- [ ] Authors
- [ ] Contributting
- [x] Keywords
- [x] Github labels
...

**Comment by agryash** [comment]
Can I take this?

**Comment by HamedNN76** [comment]
Hi @ingenuo-yag 
Unfortunately, this issue gets closed.
But in the feature, we will ask for your help
Thanks, dude.
